tab:
  header: "&4&lâœ¦ NYX WARS âœ¦\n&7Servidor Factions\n&3Bem-vindo, &b%player%"
  footer: "&8â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”\n&6ğŸŒ Site: &e%site%\n&9ğŸ’¬ Discord: &b%discord%\n&ağŸ‘¥ Online: %online% &8â”‚ &dğŸ“¶ Ping: &f%ping%ms\n&8â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"

join:
  title: "&4âœ¦ NYX WARS âœ¦"
  subtitle: "&7Servidor Factions"
  message: "&6Bem-vindo ao &cNYX WARS&6, &b%player%!"
  sound: "ENTITY_PLAYER_LEVELUP"

links:
  site: "Em manutenÃ§Ã£o"
  discord: "discord.gg/4cSu6yZy9S"
